### ISSUE TITLE
OmniPay V3

### ISSUE THREAD

**Issue by tsantos84** [descubraomundo/omnipay-pagarme#5]
OmniPay V3 is in progress and I suppose that all gateways should be upgraded to that version also. Do you have plans to make this upgrade? I'm going to start a new project that connects to Pagar.me but OmniPay V2 is incompatible with my others dependencies.

**Comment by Leuloch** [comment]
Yes!

We are also having problems with outdated dependencies. Once they release an alpha version of Omnipay V3, we will be working on the upgrade as soon as possible.
