### ISSUE TITLE
Credit card purchase with Token ( card_hash ) ?

### ISSUE THREAD

**Issue by gui-gui** [descubraomundo/omnipay-pagarme#6]
Is it possible to create a credit card charge using a token (card_hash) instead of passing the credit card details through the server? 

Thanks for your time 👍

**Comment by gpassarelli** [comment]
@gui-gui , @Leuloch  is the right person to help you with this.

**Comment by Leuloch** [comment]
@gui-gui Yes!

You can pass an array like:

```php
$transaction = $gateway->authorize(array(
  'amount'           => '10.00',
  'soft_descriptor'  => 'test', // 13 characters allowed
  'payment_method'   => 'credit_card',
  'installments'     => 5,
  'postback_url'     => 'http://application.com/api/',
  'card_hash'        => 'card_k5sT...',
  'metadata'         => array(
                            'product_id' => 'ID1111',
                            'invoice_id' => 'IV2222',
                        ),
));
```
So, you don't need to create an instance of Omnipay\Pagarme\CreditCard, just pass the card_hash!

**Comment by gui-gui** [comment]
Awesome!  thanks a lot @Leuloch  and @gpassarelli  👍
